<a href="https://colab.research.google.com/github/sreenidhi2211/Start_DataAnalytics/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NUMPY
numpy->numerical python
->working on arrays
->on matrices and linear algebra
numpy is used to access arrays faster
In numpy elements are stored in ONE continous locations(single block)

In [ ]:
!pip install numpy

In [ ]:
import numpy as np


#CREATING ARRAY
array object==ndarrray here
creating it using array() function->
1-D ARRAY=List
2-D ARRAY=combination of 1-D=Matrices


#1-D ARRAY
variable =np.array([values])
**INDEX** from 0 to n-1
accessing
print(variable[n]) for nth element
print(variable[m:n]) for m to n element

In [ ]:
x=np.array([1,2,3,4,5])

In [ ]:
y=np.array([3,4,6,8,9])

In [ ]:
print(x)

[1 2 3 4 5]


In [ ]:
print(x[0:3])

[1 2 3]


#2-D ARRAY
**HERE IT IS COMBINATION OF TWO 1-D ARRAYS(2 LISTS)**
variable=np.array([elements of 1 st row],[elements of send row] and so on )
NOTE:Elements in each row should be same
 **INDEX**(SIZE(M,N))
 FROM 0 to M-1(ROWS) ao 1st row will be 0th row
 FROM 0 to N-1(COLUMNS)
 Accesing
 print(variable[row no,clounm no])(same output without priny also)


In [ ]:
two_d=np.array([[1,3,5,7],[2,4,6,8]])

In [ ]:
print(two_d)

[[1 3 5 7]
 [2 4 6 8]]


In [ ]:
(two_d[1][2])

6

In [ ]:
print(two_d[1,2])

6


In [ ]:
print(two_d[1][1:3])

[4 6]


In [ ]:
print(two_d[0])

[1 3 5 7]


#3-D ARRAY
***IT IS COMBINATION OF 3 2-D ARRAYS**
variable=np.array([[elements of 1 2-d array],[elements of 2nd 2-D array list],[3rd 2-d array ]])
**ACCESSING**
variable([index of the 2-d array][index of the list in the 2 _d array][index of the element])

In [ ]:
three_d=np.array([[[1,2,3],[4,5,6]],[[2,4,6],[3,5,7]],[[9,8,7],[3,6,7]]])

In [ ]:
three_d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[2, 4, 6],
        [3, 5, 7]],

       [[9, 8, 7],
        [3, 6, 7]]])

In [ ]:
three_d[2][1][2]

7

In [ ]:
three_d[0][0]

array([1, 2, 3])

In [ ]:
three_d[1][1][0:2]

array([3, 5])

In [ ]:
three_d.shape

(3, 2, 3)

#NUMPY COPY&VIEW
already defined array (sayX)
->COPY
Variable=x.copy()"JUST COPIED AS IT IS"
->VIEW
Variable 1=x.view()"VIEW OF CHANGE"
"NOW"
if we change any element of X likeX[1]=1 to X[1]=32
change appears in X
but when you access the "COPY" variable (here Variable)->
the "array X is displayed as it is"(before changing the index element)
but when we access the "view" variable(here varaible 1)->
the "changed array X is displayed)


In [ ]:
z=x.copy()
a=x.view()

In [ ]:
print(z)

[1 2 3 4 5]


In [ ]:
print(a)

[1 2 3 4 5]


In [ ]:
a[2]=345

In [ ]:
a

array([  1,   2, 345,   4,   5])

In [ ]:
z

array([1, 2, 3, 4, 5])

In [ ]:
a

array([  1,   2, 345,   4,   5])

#SHAPE OF ARRAY
array name.shape

In [ ]:
x.shape

(5,)

In [ ]:
two_d.shape

(2, 4)

In [ ]:
three_d.shape

(3, 2, 3)

#RESHAPING THE ARRAY
**1D array ->2-D array**
variable.reshape(m,n)->(mxn)=size of the  1-d array,
m-1_d arrays,n-elemnets in each array
**1-D array ->3-D array**
variable.reshape(l,m,n)->(lxmxn)=size of the  1-d array.l-2_d arrays,m-lists in each 2 d array,n-elements in each list
**Any array ->1-d array**
array name.reshape(-1)

In [ ]:
b=np.array([0,1,2,3,4,5,6,7,8,9])

In [ ]:
b.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
b.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
c=np.array([9,8,7,6,5,4,3,2,1,0,9,45])

In [ ]:
c.reshape(2,3,2)

array([[[ 9,  8],
        [ 7,  6],
        [ 5,  4]],

       [[ 3,  2],
        [ 1,  0],
        [ 9, 45]]])

In [ ]:
d=c.reshape(3,2,2)

In [ ]:
c.reshape(4,3,1)

array([[[ 9],
        [ 8],
        [ 7]],

       [[ 6],
        [ 5],
        [ 4]],

       [[ 3],
        [ 2],
        [ 1]],

       [[ 0],
        [ 9],
        [45]]])

In [ ]:
d.reshape(-1)

array([ 9,  8,  7,  6,  5,  4,  3,  2,  1,  0,  9, 45])

#ITERATION
for loop
for variable in array_name:
print(variable)

In [ ]:
for i in two_d:
 print(i)

[1 3 5 7]
[2 4 6 8]


In [ ]:
for i in two_d:
  for j in i:
    print(j)

1
3
5
7
2
4
6
8


In [ ]:
for i in three_d:
  for j in i:
    print(j)

[1 2 3]
[4 5 6]
[2 4 6]
[3 5 7]
[9 8 7]
[3 6 7]


In [ ]:
for i in three_d:
  for j in i:
    for k in j:
     print(k)

1
2
3
4
5
6
2
4
6
3
5
7
9
8
7
3
6
7


# COMBINING ARRAYS
i.e concatenate
variable=np.concatenate(array1,array2)

In [ ]:
f=np.concatenate((x,y))

In [ ]:
print(f)

[  1   2 345   4   5   3   4   6   8   9]


In [ ]:
tw0_d1=np.array([[1,3,5,7],[2,4,5,6]])

In [ ]:
h=np.concatenate((two_d,tw0_d1),axis=0)

In [ ]:
print(h)

[[1 3 5 7]
 [2 4 6 8]
 [1 3 5 7]
 [2 4 5 6]]


In [ ]:
i=np.concatenate((two_d,tw0_d1),axis=1)

In [ ]:
print(i)

[[1 3 5 7 1 3 5 7]
 [2 4 6 8 2 4 5 6]]


# SEARCH ELEMENT IN ARRAY
 variable=np.search(array_name==element)
 result->index of the element

In [ ]:
np.where(x==5)

(array([4]),)

# SORT ELEMENTS
print(np.sort(array name))

In [ ]:
np.sort(x)

array([  1,   2,   4,   5, 345])

#NUMPY ZEROS,ONES,FULLS
np.zeros((index))
np.ones((index))
np.full((index),number in place of elements)

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.ones((5,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.full((6,7),10)

array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])

# ARRANGE ELEMENTS IN ARRAY
** without actually giving elements**
 np.arange(starting no of elements,ending value of elements,difference between two elements )

In [ ]:
np.arange(9,45,9)

array([ 9, 18, 27, 36])

In [ ]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

# MATHEMATICAL MANIPULATION
np.add(arra_1,arr_2)
replace->add with 1.subtract
2.multiply
3.divide
**SUM OF ELEMENTS IN THE ARRAY**
np.sum(array_name)
**MEAN**
np.mean(arra_name)

In [ ]:
np.add(x,y)

array([  4,   6, 351,  12,  14])

In [ ]:
np.subtract(x,y)

array([ -2,  -2, 339,  -4,  -4])

In [ ]:
np.multiply(x,y)

array([   3,    8, 2070,   32,   45])

In [ ]:
np.divide(y,x)

array([3.       , 2.       , 0.0173913, 2.       , 1.8      ])

In [ ]:
np.sum(three_d)

88

In [ ]:
np.sum(three_d,axis=0)

array([[12, 14, 16],
       [10, 16, 20]])

In [ ]:
np.sum(three_d,axis=1)

array([[ 5,  7,  9],
       [ 5,  9, 13],
       [12, 14, 14]])

In [ ]:
np.mean(x)


71.4

In [ ]:
np.mean(two_d)

4.5

In [ ]:
np.mean(three_d)

4.888888888888889

In [ ]:
np.median(two_d)

4.5

In [ ]:
np.median(x)

4.0

#RANDOM GENERATION OF ELEMENTS IN ARRAY
np.radom.random((index))
np.radom.randint((start_element,end_element),(index))


In [ ]:
np.random.random((2,2))

array([[0.23127738, 0.75872262],
       [0.14961317, 0.77640798]])

In [ ]:
np.random.randint(2,10,(3,3))

array([[6, 7, 4],
       [9, 5, 3],
       [2, 8, 6]])